# Generated by Django 5.2.17 on 2026-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('congratulations', 'Tebrik Mesajı'), ('message', 'Mesaj'), ('attendance_status', 'Katılım Durumu')], default='congratulations', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('attendance', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
