# Generated by Django 5.2.17 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeddingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="wedding_photos/%Y/%m/%d/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
