# Generated by Django 5.2.17 on 2026-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_weddingphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingphoto',
            name='image',
            field=models.ImageField(upload_to='wedding_photos/'),
        ),
    ]
