# Generated by Django 5.2.17 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0004_wedding_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weddingphoto",
            name="file",
            field=models.ImageField(upload_to="wedding_media/"),
        ),
        migrations.AlterModelOptions(
            name="weddingphoto",
            options={
                "verbose_name": "düğün fotoğrafı",
                "verbose_name_plural": "düğün fotoğrafları",
            },
        ),
    ]
